// This file was generated by engine on Tue Mar 08 2022
// You can extend it if you want, but leave the defaults to be required from the engine config

module.exports = {
  ...require('./internal_folder/engine/tools/engine_cli/etc/metro.config')
};
