// This file was generated by engine on Tue Mar 29 2022
// You can extend it if you want, but leave the defaults to be required from the engine config

module.exports = {
  ...require('./node_modules/engine/tools/engine_cli/etc/metro.config')
};
